app:
  db:
    mysql:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/multidatasource
        username: 
        password: 
      jpa:
        show-sql: true
        hibernate:
          # if you want to generate tables by Hibernate, set ddl-auto: create
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL57Dialect
    postgresql:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/multidatasource
        username: 
        password: 
      jpa:
        show-sql: true
        hibernate:
          # if you want to generate tables by Hibernate, set ddl-auto: create
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            # avoid warning
            jdbc:
              lob:
                non_contextual_creation: true
